spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # validate -> we'll rely on Flyway
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # FLYWAY CONFIGURATION
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: username #${spring.datasource.username}
    password: password #${spring.datasource.password}

server:
  port: 8050